// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeHyNhEwyQt3IN2YAQHd0UKjSPp0MFjCI',
    appId: '1:1019283494576:web:89cc3cac44e9510dc3cd75',
    messagingSenderId: '1019283494576',
    projectId: 'thingsboard-85bc3',
    authDomain: 'thingsboard-85bc3.firebaseapp.com',
    storageBucket: 'thingsboard-85bc3.firebasestorage.app',
    measurementId: 'G-BX9P320F4W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6P6rXC9MC56pA5nTuJu8m4KbqmW-dZK4',
    appId: '1:1019283494576:android:1b6c3e5d0aac9029c3cd75',
    messagingSenderId: '1019283494576',
    projectId: 'thingsboard-85bc3',
    storageBucket: 'thingsboard-85bc3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPF3eXJEGGneiYUwg5jgTrgX4ciTVGQZs',
    appId: '1:1019283494576:ios:bfa01413686e24bdc3cd75',
    messagingSenderId: '1019283494576',
    projectId: 'thingsboard-85bc3',
    storageBucket: 'thingsboard-85bc3.firebasestorage.app',
    iosBundleId: 'MyTbios.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPF3eXJEGGneiYUwg5jgTrgX4ciTVGQZs',
    appId: '1:1019283494576:ios:dd2dc649b5869663c3cd75',
    messagingSenderId: '1019283494576',
    projectId: 'thingsboard-85bc3',
    storageBucket: 'thingsboard-85bc3.firebasestorage.app',
    iosBundleId: 'com.example.thingsboardApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeHyNhEwyQt3IN2YAQHd0UKjSPp0MFjCI',
    appId: '1:1019283494576:web:96243dbb2179f108c3cd75',
    messagingSenderId: '1019283494576',
    projectId: 'thingsboard-85bc3',
    authDomain: 'thingsboard-85bc3.firebaseapp.com',
    storageBucket: 'thingsboard-85bc3.firebasestorage.app',
    measurementId: 'G-LB0BJBEBKL',
  );
}
